gha_enabled: true
blocked_dirs: []
draft: false
description: |
  Sweep AI must follow the repository guidelines in .github/AGENTS.md.
rules:
  - "Read .github/AGENTS.md first; it overrides these rules."
  - "Format code with magex format:fix"
  - "Lint with 'magex lint'"
  - "Run 'magex test' before committing"
  - "Commit messages refer to AGENTS.md"
  - "Run 'magex deps:tidy' after import changes"
  - "Report vulnerabilities privately following SECURITY.md"
